name: Remote Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install OpenSSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests for server app
        run: yarn test-server-deploy

      - name: Deploy to remote server
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.REMOTE_SERVER_IP_ADDR }} >> $HOME/.ssh/known_hosts
          ssh_output=$(ssh -o StrictHostKeyChecking=no -l ${{ secrets.REMOTE_SERVER_USER }} ${{ secrets.REMOTE_SERVER_IP_ADDR }} "sudo BASH_ENV=\$HOME/.bashrc bash -l -c './print_home.sh'")
          home_path=$(echo "$ssh_output" | grep "User's Home directory" | awk '{print $NF}')
          echo "Home path: $home_path"
